server {
  listen 80;
  server_name _;
  location = /health {
    root /usr/share/nginx/html;
    try_files /health =404;
  }
  location /api/ {
    proxy_pass http://backend:8080/api/;
  }
  location /health/ {
    proxy_pass http://backend:8080/health/;
  }
  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }
}
